package junit.tests;

import junit.framework.AssertionFailedError;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestFailure;
import junit.framework.TestResult;
import junit.tests.framework.TestCaseTest.TornDown;

/**
 * A helper test case for testing whether the testing method
 * is run.
 */
public class WasRun extends TestCase {
	public boolean fWasRun= false;
		protected void runTest() {
			fWasRun= true;
		}
		public void testNamelessTestCase() {
			TestCase t= new TestCase() {};
			try {
				t.run();
				fail();
			} catch (AssertionFailedError e) {
			}
		}
		public void testTearDownSetupFails() {
			TornDown fails= new TornDown() {
				protected void setUp() {
					throw new Error();
				}
			};
			verifyError(fails);
			assertTrue(!fails.fTornDown);
		}
		public void testExceptionRunningAndTearDown() {
			// With 1.4, we should
			// wrap the exception thrown while running with the exception thrown
			// while tearing down
			Test t= new TornDown() {
				public void tearDown() {
					throw new Error("tearingDown");
				}
			};
			TestResult result= new TestResult();
			t.run(result);
			TestFailure failure= (TestFailure) result.errors().nextElement();
			assertEquals("running", failure.thrownException().getMessage());
		}
}